# Generated by Django 4.2.3 on 2023-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('created', 'Добавлен'), ('moderated', 'На модерации'), ('published', 'Опубликован')], default='moderated', max_length=20, verbose_name='статус'),
        ),
    ]
